// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDQO0Eepn8DTPXAKcSaBmhu5P7Uk2iA1L0',
//     appId: '1:384807786158:web:de9188115ca94092297f3f',
//     messagingSenderId: '384807786158',
//     projectId: 'crypto-facc2',
//     authDomain: 'crypto-facc2.firebaseapp.com',
//     storageBucket: 'crypto-facc2.appspot.com',
//     measurementId: 'G-BBF8W1P1F8',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCUyIXL3vLgA2B3u1xa-EXRZbXdq000B54',
//     appId: '1:384807786158:android:f9be1da1ea8740e9297f3f',
//     messagingSenderId: '384807786158',
//     projectId: 'crypto-facc2',
//     storageBucket: 'crypto-facc2.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB1AHjO65zzgKrkJKFq3yNBNI2KrYdMeMU',
//     appId: '1:384807786158:ios:cea375e0fc1bc7ed297f3f',
//     messagingSenderId: '384807786158',
//     projectId: 'crypto-facc2',
//     storageBucket: 'crypto-facc2.appspot.com',
//     iosClientId: '384807786158-objm2f9ccui46gg2cpse74r26lr8bdno.apps.googleusercontent.com',
//     iosBundleId: 'com.example.cryptoProject',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB1AHjO65zzgKrkJKFq3yNBNI2KrYdMeMU',
//     appId: '1:384807786158:ios:cea375e0fc1bc7ed297f3f',
//     messagingSenderId: '384807786158',
//     projectId: 'crypto-facc2',
//     storageBucket: 'crypto-facc2.appspot.com',
//     iosClientId: '384807786158-objm2f9ccui46gg2cpse74r26lr8bdno.apps.googleusercontent.com',
//     iosBundleId: 'com.example.cryptoProject',
//   );
// }
